[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["FlorianJacta <98709993+FlorianJacta@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9, <3.13"
numpy = "1.26"
taipy = "4.0.0.dev0"
rembg = "^2.0.58"
pillow = "^10.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
